"lmom.test.all" <-
function(data) {
    WIDTH <- getOption("width")
    DASH  <- rep("-",WIDTH)
    cat(c(DASH,"\n"),sep="")
    lmom.test.exp(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.gam(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.gev(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.glo(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.gno(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.gpa(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.gum(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.kap(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.nor(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.pe3(data)
    cat(c(DASH,"\n"),sep="")
    lmom.test.wak(data)
    cat(c(DASH,"\n"),sep="")
    return()
}

